import { 
  Brain, 
  Eye, 
  Database, 
  Code2, 
  Layers,
  Server,
  Globe,
  Sparkles
} from 'lucide-react'

const About = () => {
  const highlights = [
    {
      icon: <Brain className="w-5 h-5 text-zinc-300" />,
      title: "Deep Learning Model",
      text: "Modified CNN with Global Average Pooling and Dropout, trained on the CIFAKE dataset."
    },
    {
      icon: <Eye className="w-5 h-5 text-zinc-300" />,
      title: "Explainable AI Ready",
      text: "Architecture supports Grad-CAM visualizations for interpreting model decisions."
    },
    {
      icon: <Database className="w-5 h-5 text-zinc-300" />,
      title: "CIFAKE Dataset",
      text: "Trained on 60,000 real and 60,000 synthetic images generated by latent diffusion models."
    },
    {
      icon: <Layers className="w-5 h-5 text-zinc-300" />,
      title: "Full-Stack System",
      text: "React frontend, Express backend, and FastAPI ML service — cleanly separated and deployed."
    }
  ]

  const techStack = [
    { name: "React + Tailwind CSS", role: "Frontend", icon: <Globe className="w-4 h-4 text-zinc-300" /> },
    { name: "Express.js", role: "Backend API", icon: <Server className="w-4 h-4 text-zinc-300" /> },
    { name: "FastAPI + TensorFlow", role: "ML Inference", icon: <Brain className="w-4 h-4 text-zinc-300" /> },
    { name: "Modified CNN", role: "Detection Model", icon: <Eye className="w-4 h-4 text-zinc-300" /> },
  ]

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 py-12 space-y-20">
      
      {/* Header */}
      <section className="max-w-2xl space-y-4">
        <p className="text-zinc-400 text-sm font-medium tracking-wide uppercase">
          About the Project
        </p>
        <h1 className="text-3xl sm:text-4xl font-bold text-zinc-100 tracking-tight">
          Z-Vision
        </h1>
        <p className="text-zinc-400 text-lg leading-relaxed">
          An intelligent system designed to detect AI-generated synthetic images 
          using Convolutional Neural Networks and modern full-stack technology.
        </p>
      </section>

      {/* Overview */}
      <section className="grid grid-cols-1 lg:grid-cols-12 gap-10">
        <div className="lg:col-span-7 space-y-4">
          <h2 className="text-xl font-semibold text-zinc-100 flex items-center gap-2">
            <Code2 className="w-5 h-5 text-zinc-300" />
            Project Overview
          </h2>
          <div className="space-y-4 text-zinc-400 leading-relaxed">
            <p>
              With the rapid advancement of generative AI — especially Latent Diffusion Models — 
              it has become extremely difficult for humans to distinguish between real photographs 
              and AI-generated images. This creates serious challenges related to misinformation, 
              privacy, and digital trust.
            </p>
            <p>
              <span className="text-zinc-100 font-medium">Z-Vision</span> addresses this problem by providing 
              an automated detection system. Users can upload an image and instantly receive a 
              prediction (Real or Fake) along with a confidence score.
            </p>
          </div>
        </div>

        {/* Stats */}
        <div className="lg:col-span-5">
          <div className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-6 space-y-5">
            <div className="flex items-center gap-2 text-sm text-zinc-400">
              <Sparkles className="w-4 h-4 text-zinc-300" />
              Model Performance
            </div>
            
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-zinc-400 text-sm">Accuracy</span>
                <span className="text-xl font-bold text-zinc-100">89.77%</span>
              </div>
              <div className="w-full h-1.5 bg-zinc-800 rounded-full overflow-hidden">
                <div className="h-full bg-zinc-300 rounded-full" style={{ width: '89.77%' }} />
              </div>

              <div className="flex items-center justify-between pt-2">
                <span className="text-zinc-400 text-sm">Precision</span>
                <span className="text-xl font-bold text-zinc-100">83.43%</span>
              </div>
              <div className="w-full h-1.5 bg-zinc-800 rounded-full overflow-hidden">
                <div className="h-full bg-zinc-400 rounded-full" style={{ width: '83.43%' }} />
              </div>

              <div className="flex items-center justify-between pt-2">
                <span className="text-zinc-400 text-sm">Recall</span>
                <span className="text-xl font-bold text-zinc-100">99.07%</span>
              </div>
              <div className="w-full h-1.5 bg-zinc-800 rounded-full overflow-hidden">
                <div className="h-full bg-zinc-200 rounded-full" style={{ width: '99.07%' }} />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Highlights */}
      <section className="space-y-6">
        <div className="max-w-xl">
          <h2 className="text-xl font-semibold text-zinc-100 mb-1">Key Highlights</h2>
          <p className="text-zinc-400 text-sm">Core capabilities of the system</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {highlights.map((item, index) => (
            <div
              key={index}
              className="flex gap-4 p-5 rounded-2xl bg-zinc-900/40 border border-zinc-800 hover:border-zinc-700 transition-colors"
            >
              <div className="shrink-0 p-2.5 rounded-xl bg-zinc-800 h-fit border border-zinc-700">
                {item.icon}
              </div>
              <div>
                <h3 className="font-semibold text-zinc-100 mb-1">{item.title}</h3>
                <p className="text-sm text-zinc-400 leading-relaxed">{item.text}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Tech Stack */}
      <section className="space-y-6">
        <div className="max-w-xl">
          <h2 className="text-xl font-semibold text-zinc-100 mb-1">Technology Stack</h2>
          <p className="text-zinc-400 text-sm">Tools and frameworks used in this project</p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {techStack.map((tech, index) => (
            <div
              key={index}
              className="flex items-center justify-between p-4 rounded-xl bg-zinc-900/40 border border-zinc-800"
            >
              <div className="flex items-center gap-3">
                {tech.icon}
                <span className="font-medium text-zinc-100">{tech.name}</span>
              </div>
              <span className="text-xs text-zinc-400 bg-zinc-800 px-2.5 py-1 rounded-full border border-zinc-700">
                {tech.role}
              </span>
            </div>
          ))}
        </div>
      </section>

      {/* Disclaimer */}
      <section className="max-w-3xl p-5 rounded-2xl bg-zinc-900/40 border border-zinc-700">
        <p className="text-sm text-zinc-400 leading-relaxed">
          <span className="font-semibold text-zinc-200">Note:</span> This project is developed for 
          educational and research purposes. Detection results should not be considered 100% definitive, 
          as generative models continue to improve rapidly. The model performs best on images similar 
          to the CIFAKE training distribution.
        </p>
      </section>
    </div>
  )
}

export default About