import { ShieldCheck, Brain, Eye, Database, Code2, Layers } from 'lucide-react'

const About = () => {
  const techStack = [
    { name: "React + Tailwind CSS", role: "Frontend" },
    { name: "Express.js", role: "Backend API" },
    { name: "Python FastAPI", role: "ML Inference" },
    { name: "CNN + Grad-CAM", role: "Detection & Explainability" },
  ]

  const highlights = [
    {
      icon: <Brain className="w-6 h-6 text-cyan-400" />,
      title: "Deep Learning Model",
      text: "A modified Convolutional Neural Network is used to classify images as Real or AI-Generated."
    },
    {
      icon: <Eye className="w-6 h-6 text-blue-400" />,
      title: "Explainable AI",
      text: "Grad-CAM heatmaps highlight the regions of the image that influenced the model’s decision."
    },
    {
      icon: <Database className="w-6 h-6 text-purple-400" />,
      title: "Dataset",
      text: "Built using real images from CIFAR-10 style data and synthetic images generated by latent diffusion models."
    },
    {
      icon: <Layers className="w-6 h-6 text-green-400" />,
      title: "Full Stack Architecture",
      text: "React frontend (Vercel) + Express backend + Python ML service (Render) for clean separation of concerns."
    }
  ]

  return (
    <div className="max-w-4xl mx-auto space-y-16 py-8">
      {/* Header */}
      <div className="text-center">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 mb-6 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-cyan-400 text-sm">
          <ShieldCheck className="w-4 h-4" />
          About the Project
        </div>
        <h1 className="text-4xl font-bold mb-4">FakeVision</h1>
        <p className="text-lg text-slate-400 max-w-2xl mx-auto leading-relaxed">
          An intelligent system designed to detect AI-generated synthetic images 
          using Convolutional Neural Networks and Explainable AI techniques.
        </p>
      </div>

      {/* Project Description */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold flex items-center gap-2">
          <Code2 className="w-6 h-6 text-cyan-400" />
          Project Overview
        </h2>
        <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 space-y-4 text-slate-300 leading-relaxed">
          <p>
            With the rapid advancement of generative AI (especially Latent Diffusion Models), 
            it has become extremely difficult for humans to distinguish between real photographs 
            and AI-generated images. This creates serious challenges related to misinformation, 
            privacy, and digital trust.
          </p>
          <p>
            <strong className="text-white">FakeVision</strong> addresses this problem by providing 
            an automated detection system. Users can upload an image and instantly receive a 
            prediction (Real or Fake) along with a visual explanation of the result.
          </p>
        </div>
      </section>

      {/* Key Highlights */}
      <section>
        <h2 className="text-2xl font-semibold mb-6">Key Highlights</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {highlights.map((item, index) => (
            <div
              key={index}
              className="p-5 rounded-xl bg-slate-900/60 border border-slate-800 hover:border-slate-700 transition-colors"
            >
              <div className="flex items-center gap-3 mb-3">
                {item.icon}
                <h3 className="font-semibold text-lg">{item.title}</h3>
              </div>
              <p className="text-slate-400 text-sm leading-relaxed">{item.text}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Tech Stack */}
      <section>
        <h2 className="text-2xl font-semibold mb-6">Technology Stack</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {techStack.map((tech, index) => (
            <div
              key={index}
              className="flex items-center justify-between p-4 rounded-xl bg-slate-900/60 border border-slate-800"
            >
              <span className="font-medium">{tech.name}</span>
              <span className="text-sm text-cyan-400 bg-cyan-500/10 px-3 py-1 rounded-full">
                {tech.role}
              </span>
            </div>
          ))}
        </div>
      </section>

      {/* Disclaimer */}
      <section className="p-5 rounded-xl bg-amber-500/5 border border-amber-500/20">
        <p className="text-sm text-amber-200/90 leading-relaxed">
          <strong>Note:</strong> This project is developed for educational and research purposes. 
          Detection results should not be considered 100% definitive, as generative models continue to improve rapidly.
        </p>
      </section>
    </div>
  )
}

export default About